<?php

/**
 * PlugincrMediaGalleryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugincrMediaGalleryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugincrMediaGalleryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugincrMediaGallery');
    }
}