<?php

/**
 * PlugincrMediaGalleryContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugincrMediaGalleryContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugincrMediaGalleryContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugincrMediaGalleryContent');
    }
}