generator:
  class: sfDoctrineGenerator
  param:
    model_class:           crMediaGalleryContent
    theme:                 thexAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          cr_media_gallery_content
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
#        gallery_id: { title: Calin }
      list:
        title: Media content
        display: [name, gallery_id, type, is_published, allow_comments, allow_votes]
      filter:
        display: [name, description, type, gallery_id]
      form:
        display:
          "General information": [name, description, gallery_id, type, resize_w, resize_h, content]
          "Optional information": [tags, slug, allow_comments, is_published, allow_votes]
      edit:
        title: Editing gallery content "%%name%%"
      new:
        title: Add new content to gallery
