all:
  stylesheets:
    - /crWebPlugin/css/prettyPhoto.css
    - /crMediaPlugin/css/crMediaPlugin.css

  javascripts:
    - /crMediaPlugin/js/crMediaPlugin.js
    
indexSuccess:
  javascripts:
    - /crWebPlugin/js/jquery.prettyPhoto.js