indexSuccess:
  stylesheets:
    - /crWebPlugin/css/prettyPhoto.css
    - /crMediaPlugin/css/crMediaPlugin.css

  javascripts:
    - /crWebPlugin/js/jquery.prettyPhoto.js
    - /crMediaPlugin/js/crMediaPlugin.js
editSuccess:
  stylesheets:
    - /crWebPlugin/css/prettyPhoto.css
    - /crMediaPlugin/css/crMediaPlugin.css

  javascripts:
    - /crWebPlugin/js/jquery.prettyPhoto.js
    - /crMediaPlugin/js/crMediaPlugin.js